### ISSUE TITLE
Incorrect time in "Recent Emails"

### ISSUE THREAD

**Issue by the-Jack-D** [s1t5/mail-archiver#95]
On the Dashboard, in "Recent Emails," the time on the message is incorrect.

For example, I have a message that shows this date and time: 

<img width="156" height="33" alt="Image" src="https://github.com/user-attachments/assets/dc0c0e8e-0fd4-4a86-80f8-c4a0c5f02a70" />

When I click on the message to view it, the date and time shows this way:

<img width="490" height="33" alt="Image" src="https://github.com/user-attachments/assets/7682d81e-3498-4b2c-9256-e3752f6e819d" />

**Comment by the-Jack-D** [comment]
Following up on this, in the example I gave in the original post, Gmail shows the email as arriving at 9:36am.

Here are a couple of other weird examples from the last few emails:

- Gmail shows: 9:51am, Recent Emails: 9:51am, Archived email detail: 1:51pm
- Gmail shows: 9:48am, Recent Emails: 2:48am, Archived email detail: 6:48am
- Gmail shows: 9:20am, Recent Emails: 9:20am, Archived email detail: 1:20pm

**Comment by s1t5** [comment]
I have fixed the differences between the dashboard and the archive, which were caused, among other things, by an incorrect time zone calculation.
I now consistently display the sent date of the emails in both places. What may still be an issue here is that Gmail does not show the sent date, but rather the received date. 
The error with the aforementioned difference between the dashboard and the archive will be fixed in the next version.

**Comment by the-Jack-D** [comment]
It still isn't quite right. I just received an email 7 minutes ago, at 1:29pm. However, in both Recent Emails and in the email detail, it shows 10:29am.

**Comment by s1t5** [comment]
Could you forward me the email from your inbox if possible? Then I can take a closer look at it.

**Comment by migro3466** [comment]
Great app! 👏
I’m not entirely sure if this issue has already been fixed.
I’ve set the time zone in the environment variables, but the timestamps/dates are still shown in UTC in the archive and also in the search. I’m archiving emails from iCloud and Strato.de accounts.

**Comment by sbach89** [comment]
<img width="1602" height="155" alt="Image" src="https://github.com/user-attachments/assets/8b1d0250-bff7-46a0-b2c3-ea653d384140" />

This is still not fixed. This issue should also be reopened as I almost opened another one.

I'm also not using gmail, but a private mail server. Webmail and other mail clients have correct time.

**Comment by s1t5** [comment]
I will look into this again.

**Comment by s1t5** [comment]
@sbach89 I have now added a conversion of the time to the target time zone. This must be specified in the docker compose (as shown in the example in the readme).
Please update your container to the dev tag and give me some brief feedback! Please note that the change only affects emails that are archived from now on.

**Comment by sbach89** [comment]
Thanks @s1t5, currently testing now, will provide update once I get more emails. So far the one that came in after updating has the correct time!
